name: lab04
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.0.7
  encrypted_shared_preferences: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - images/beef.jpg
    - images/chicken.jpg
    - images/pork.jpg
    - images/seafood.jpg
    - images/maindish.jpg
    - images/salad.jpg
    - images/sidedishes.jpg
    - images/crockpot.jpg
    - images/icecream.jpg
    - images/brownies.jpg
    - images/pies.jpg
    - images/cookies.jpg
